[[redirects]]
  from = "/api/*"
  to = "http://aa09e3ae27a144cd0aaf0fbce7f0ab1c-bcccf20eeb9b21bd.elb.ap-south-1.amazonaws.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "http"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200