[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

  [[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200